### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by remi0s** [ColinKinloch/LatinIME_apk#2]
I'm trying to build the app using the commands listed but i get the error 

  No rule to make target `C:/Users/username/AppData/Local/Android/Sdk/ndk-bundle/build//../build/core/build-host-static-library.mk'

 I have tried to build it in windows and ubuntu 16.04. Can you help me solve this?

		process_begin: CreateProcess(NULL, "", ...) failed.
	C:/Users/username/Desktop/LatinIME_apk/LatinIME/native/jni/HostUnitTests.mk:39: C:/Users/username/AppData/Local/Android/Sdk/ndk-bundle/build//../build/core/build-host-static-library.mk: No such file or directory
	make: *** No rule to make target `C:/Users/username/AppData/Local/Android/Sdk/ndk-bundle/build//../build/core/build-host-static-library.mk'.  Stop.
	External native generate JSON debug: JSON generation completed with problems
	:generateJsonModelDebug FAILED

	FAILURE: Build failed with an exception.

	* What went wrong:
	Execution failed for task ':generateJsonModelDebug'.
	> Build command failed.
	  Error while executing process C:\Users\username\AppData\Local\Android\Sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=C:\Users\username\Desktop\LatinIME_apk\LatinIME\native\jni\Android.mk NDK_APPLICATION_MK=C:\Users\username\Desktop\LatinIME_apk\LatinIME\native\jni\Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 APP_PLATFORM=android-15 NDK_OUT=C:/Users/username/Desktop/LatinIME_apk/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=C:\Users\username\Desktop\LatinIME_apk\build\intermediates\ndkBuild\debug\lib APP_CFLAGS+=-w APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
	  process_begin: CreateProcess(NULL, "", ...) failed.
	  C:/Users/username/Desktop/LatinIME_apk/LatinIME/native/jni/HostUnitTests.mk:39: C:/Users/username/AppData/Local/Android/Sdk/ndk-bundle/build//../build/core/build-host-static-library.mk: No such file or directory
	  make: *** No rule to make target `C:/Users/username/AppData/Local/Android/Sdk/ndk-bundle/build//../build/core/build-host-static-library.mk'.  Stop.

	* Try:
	Run with --info or --debug option to get more log output. Run with --scan to get full insights.

	* Exception is:
	org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':generateJsonModelDebug'.
			at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
			at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
			at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
			at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
			at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
			at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
			at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
			at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
			at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
			at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
			at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
			at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
			at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
			at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
			at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
			at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
			at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
			at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
			at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
			at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
			at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
			at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
			at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
			at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
			at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
			at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
			at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
			at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
			at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
			at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	Caused by: org.gradle.internal.UncheckedException: Build command failed.
	Error while executing process C:\Users\username\AppData\Local\Android\Sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=C:\Users\username\Desktop\LatinIME_apk\LatinIME\native\jni\Android.mk NDK_APPLICATION_MK=C:\Users\username\Desktop\LatinIME_apk\LatinIME\native\jni\Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 APP_PLATFORM=android-15 NDK_OUT=C:/Users/username/Desktop/LatinIME_apk/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=C:\Users\username\Desktop\LatinIME_apk\build\intermediates\ndkBuild\debug\lib APP_CFLAGS+=-w APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
	process_begin: CreateProcess(NULL, "", ...) failed.
	C:/Users/username/Desktop/LatinIME_apk/LatinIME/native/jni/HostUnitTests.mk:39: C:/Users/username/AppData/Local/Android/Sdk/ndk-bundle/build//../build/core/build-host-static-library.mk: No such file or directory
	make: *** No rule to make target `C:/Users/username/AppData/Local/Android/Sdk/ndk-bundle/build//../build/core/build-host-static-library.mk'.  Stop.

			at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:63)
			at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:40)
			at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:76)
			at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
			at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
			at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
			at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:780)
			at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:747)
			at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
			at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
			at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
			at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
			at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
			at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
			at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
			... 29 more
	Caused by: Build command failed.
	Error while executing process C:\Users\username\AppData\Local\Android\Sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=C:\Users\username\Desktop\LatinIME_apk\LatinIME\native\jni\Android.mk NDK_APPLICATION_MK=C:\Users\username\Desktop\LatinIME_apk\LatinIME\native\jni\Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 APP_PLATFORM=android-15 NDK_OUT=C:/Users/username/Desktop/LatinIME_apk/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=C:\Users\username\Desktop\LatinIME_apk\build\intermediates\ndkBuild\debug\lib APP_CFLAGS+=-w APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
	process_begin: CreateProcess(NULL, "", ...) failed.
	C:/Users/username/Desktop/LatinIME_apk/LatinIME/native/jni/HostUnitTests.mk:39: C:/Users/username/AppData/Local/Android/Sdk/ndk-bundle/build//../build/core/build-host-static-library.mk: No such file or directory
	make: *** No rule to make target `C:/Users/username/AppData/Local/Android/Sdk/ndk-bundle/build//../build/core/build-host-static-library.mk'.  Stop.

			at com.android.build.gradle.tasks.ExternalNativeBuildTaskUtils.executeBuildProcessAndLogError(ExternalNativeBuildTaskUtils.java:244)
			at com.android.build.gradle.tasks.NdkBuildExternalNativeJsonGenerator.executeProcess(NdkBuildExternalNativeJsonGenerator.java:195)
			at com.android.build.gradle.tasks.ExternalNativeJsonGenerator.buildAndPropagateException(ExternalNativeJsonGenerator.java:323)
			at com.android.build.gradle.tasks.ExternalNativeJsonGenerator.build(ExternalNativeJsonGenerator.java:188)
			at com.android.build.gradle.tasks.ExternalNativeBuildJsonTask.build(ExternalNativeBuildJsonTask.java:35)
			at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
			... 41 more

**Comment by ColinKinloch** [comment]
I've been compiling this on a mac which was triggering [this](https://github.com/LineageOS/android_packages_inputmethods_LatinIME/blob/3a460697c6da3550679c0a6551d61161f40431d6/native/jni/HostUnitTests.mk#L20).
Luckily there is [this](https://github.com/LineageOS/android_packages_inputmethods_LatinIME/blob/3a460697c6da3550679c0a6551d61161f40431d6/native/jni/HostUnitTests.mk#L16) a few lines before, so if you set the environment variable TARGET_BUILD_APPS to anything it should compile.
I've just set up CI builds on gitlab so if you don't feel like compiling it yourself you can download it [here](https://gitlab.com/ColinKinloch/LatinIME_apk/-/jobs/artifacts/master/raw/build/outputs/apk/debug/LatinIME-debug.apk?job=build).

**Comment by remi0s** [comment]
You kind sir helped me alot! With the changes you currently made it is building on my windows pc. Thank you very much.

[ OFFTOPIC]
If u allow me to ask you something, since you seem to know great deal of android programming, i'm encountering a strange issue.
The reason i wanted to use your github to compile the aosp keyboard is because i [allready had built an application named typeofmood](https://github.com/remi0s/typeofmood) with external build libjni_latinime.so(after i have changed the classpath to my own project name{com.android.inputmethod ->typeofmood.ime) libraries and it was working for all the versions except for oreo 8.0 and 8.1 with the error bellow. So i thought there was missing something from the original build and i should try to build it from the aosp tree. Building it with your git repo and taking the libraries didnt help the issue BUT i figured out this:
if i install the app through android studio to the emulator it is crashing BUT if i just install it using /.gradlew installDebug it is not crushing, and its working properly!

Do you have any idea why this would ever happen?Isn't android studio using the same ./gradlew installDebug command to install the app?


the error produced using android studio to install:

`

		06-10 15:33:55.704 2491-2491/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
		06-10 15:33:55.705 2491-2491/? A/DEBUG: Build fingerprint: 'google/sdk_gphone_x86/generic_x86:8.1.0/OSM1.180201.007/4586646:user/release-keys'
			Revision: '0'
			ABI: 'x86'
			pid: 2465, tid: 2486, name: ExecutorUtils  >>> typeofmood.ime <<<
			signal 7 (SIGBUS), code 2 (BUS_ADRERR), fault addr 0x98991e5c
				eax 992bcc90  ebx 996f7578  ecx 98991e5c  edx 00000000
				esi 0006dde4  edi 00fcce5c
		06-10 15:33:55.706 2491-2491/? A/DEBUG:     xcs 00000073  xds 0000007b  xes 0000007b  xfs 0000003b  xss 0000007b
				eip 995afb94  ebp 992bcc88  esp 992bcc30  flags 00010216
		06-10 15:33:55.715 2491-2491/? A/DEBUG: backtrace:
				#00 pc 000e5b94  /data/app/typeofmood.ime-P--rl2Q0BRcXLVPaj-7ajQ==/lib/x86/libjni_latinime.so (latinime::FormatUtils::detectFormatVersion(latinime::ReadOnlyByteArrayView)+100)
				#01 pc 0009f9aa  /data/app/typeofmood.ime-P--rl2Q0BRcXLVPaj-7ajQ==/lib/x86/libjni_latinime.so (latinime::DictionaryStructureWithBufferPolicyFactory::newPolicyForFileDict(char const*, int, int)+490)
				#02 pc 0009f32d  /data/app/typeofmood.ime-P--rl2Q0BRcXLVPaj-7ajQ==/lib/x86/libjni_latinime.so (latinime::DictionaryStructureWithBufferPolicyFactory::newPolicyForExistingDictFile(char const*, int, int, bool)+285)
				#03 pc 00079bde  /data/app/typeofmood.ime-P--rl2Q0BRcXLVPaj-7ajQ==/lib/x86/libjni_latinime.so
				#04 pc 00648267  /system/lib/libart.so (art_quick_generic_jni_trampoline+71)
				#05 pc 00642432  /system/lib/libart.so (art_quick_invoke_static_stub+418)
				#06 pc 001160f9  /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+265)
				#07 pc 0032153f  /system/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+335)
				#08 pc 0031b82b  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb1ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+699)
				#09 pc 0062b1b6  /system/lib/libart.so (MterpInvokeStaticRange+198)
				#10 pc 00633721  /system/lib/libart.so (artMterpAsmInstructionStart+15265)
				#11 pc 002f3a2b  /system/lib/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool)+539)
				#12 pc 002fa2e7  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*)+231)
		06-10 15:33:55.716 2491-2491/? A/DEBUG:     #13 pc 0031b80b  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb1ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+667)
				#14 pc 0062afbf  /system/lib/libart.so (MterpInvokeDirectRange+335)
				#15 pc 006336a1  /system/lib/libart.so (artMterpAsmInstructionStart+15137)
				#16 pc 002f3a2b  /system/lib/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool)+539)
				#17 pc 002fa2e7  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*)+231)
				#18 pc 0031b80b  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb1ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+667)
				#19 pc 0062afbf  /system/lib/libart.so (MterpInvokeDirectRange+335)
				#20 pc 006336a1  /system/lib/libart.so (artMterpAsmInstructionStart+15137)
				#21 pc 002f3a2b  /system/lib/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool)+539)
				#22 pc 002fa2e7  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*)+231)
				#23 pc 0031b80b  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb1ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+667)
				#24 pc 0062afbf  /system/lib/libart.so (MterpInvokeDirectRange+335)
				#25 pc 006336a1  /system/lib/libart.so (artMterpAsmInstructionStart+15137)
				#26 pc 002f3a2b  /system/lib/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool)+539)
				#27 pc 002fa2e7  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*)+231)
				#28 pc 0031a78a  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+810)
				#29 pc 0062964a  /system/lib/libart.so (MterpInvokeStatic+282)
				#30 pc 00633421  /system/lib/libart.so (artMterpAsmInstructionStart+14497)
				#31 pc 002f3a2b  /system/lib/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool)+539)
				#32 pc 002fa2e7  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*)+231)
				#33 pc 0031a78a  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+810)
				#34 pc 00627e14  /system/lib/libart.so (MterpInvokeVirtual+756)
				#35 pc 006332a1  /system/lib/libart.so (artMterpAsmInstructionStart+14113)
				#36 pc 002f3a2b  /system/lib/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool)+539)
				#37 pc 002fa2e7  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*)+231)
				#38 pc 0031a78a  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+810)
				#39 pc 00628fdf  /system/lib/libart.so (MterpInvokeInterface+1647)
				#40 pc 006334a1  /system/lib/libart.so (artMterpAsmInstructionStart+14625)
				#41 pc 002f3a2b  /system/lib/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool)+539)
				#42 pc 002fa2e7  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*)+231)
				#43 pc 0031a78a  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+810)
				#44 pc 00628fdf  /system/lib/libart.so (MterpInvokeInterface+1647)
				#45 pc 006334a1  /system/lib/libart.so (artMterpAsmInstructionStart+14625)
				#46 pc 002f3a2b  /system/lib/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool)+539)
				#47 pc 002fa2e7  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*)+231)
				#48 pc 0031a78a  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+810)
				#49 pc 006285be  /system/lib/libart.so (MterpInvokeSuper+1710)
				#50 pc 00633321  /system/lib/libart.so (artMterpAsmInstructionStart+14241)
				#51 pc 002f3a2b  /system/lib/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool)+539)
				#52 pc 002fa2e7  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*)+231)
				#53 pc 0031a78a  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+810)
				#54 pc 00628fdf  /system/lib/libart.so (MterpInvokeInterface+1647)
				#55 pc 006334a1  /system/lib/libart.so (artMterpAsmInstructionStart+14625)
				#56 pc 002f3a2b  /system/lib/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool)+539)
				#57 pc 002fa2e7  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*)+231)
				#58 pc 0031a78a  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+810)
				#59 pc 00627e14  /system/lib/libart.so (MterpInvokeVirtual+756)
				#60 pc 006332a1  /system/lib/libart.so (artMterpAsmInstructionStart+14113)
		06-10 15:33:55.717 2491-2491/? A/DEBUG:     #61 pc 002f3a2b  /system/lib/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool)+539)
				#62 pc 002fa2e7  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*)+231)
				#63 pc 0031a78a  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+810)

`

**Comment by ColinKinloch** [comment]
I don't think I can help you.
I usually avoid integrated dev tools like android studio, you tend to end up with obscure undebuggable errors.
Even gradle with the android plugin are a hassle to work with.
